#!/usr/bin/env bash
# This script prints "Best school" 10 times
i="Best School"
for i in "Best School"
do
    echo "$i"
    echo "$i"
    echo "$i"
    echo "$i"
    echo "$i"
    echo "$i"
    echo "$i"
    echo "$i"
    echo "$i"
    echo "$i"
done
