#!/usr/bin/env bash
# script to display fizz buzz on numbers 0-100 fizz number is multiple of 3 buzz is multiple of 5
for i in {1..100}
do
    if [ $(($i % 3)) = 0 ]
    then
	echo "Fizz"
    fi
    if [ $(($i % 5)) = 0 ]
    then
	echo "Buzz"
    fi
    if [ $(($i % 3)) = 0 ] && [ $(($i % 5)) = 0 ]
    then
	echo "FizzBuzz"
    else
	echo "$i"
    fi
done
