#!/usr/bin/env bash
# shell script to print unlucky numbers from different countries
i=1
while [ $i -le 20 ]
do
    case $i in
	4)
	    echo "$i"
	    echo "back luck from China"
	    ;;
	9)
	    echo "$i"
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "$i"
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo "$i"
	    ;;
    esac
    ((i++))
done
