#!/usr/bin/env bash
# Script to print out the time per each hour
hour=0
minute=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    while [ $minute -le 59 ]
    do
	echo "$minute"
	((minute++))
    done
    ((hour++))
    minute=0
done
