#!/usr/bin/env bash
# Script to check for file type
SCHOOL=school
if [ ! -e $SCHOOL ]
then
    echo "school file does not exist"
else
    echo "school file exists"
    if [ -s $SCHOOL ]
    then
	echo "school file is not empty"
	if [ -f $SCHOOL ]
	then
	    echo "school is regular file"
	fi
    else
	echo "school file is empty"
	if [ -f $SCHOOL ]
	then
	    echo "school is regular file"
	fi
    fi
fi    
