#!/usr/bin/env bash
# this script is to manipulate the manage_my_process
# Get postional arguments
PROC="$1"
case $PROC in
	start)
	    ./manage_my_process &
	    echo "$!" >> /var/run/my_process.pid &
	    echo "manage_my_process started"
	    ;;
	stop)
	    pkill -f './manage_my_process' &
	    rm /var/run/my_process.pid &
	    echo "manage_my_process stopped"
	    ;;
	restart)
	    pkill -f './manage_my_process' &
	    rm /var/run/my_process.pid
	    ./manage_my_process &
	    echo "$!" >> /var/run/my_process.pid
	    echo "manage_my_process restarted"
	    ;;
	*)
	    echo "Usage: manage_my_process {start|stop|restart}"
	    ;;
esac
