#!/usr/bin/env bash
# Script to kill script 4
pkill -15 -f 'bash ./4-to_infinity_and_beyond'
STATUS="$?"
if [ $STATUS == 0 ]
then
    echo "$STATUS One or more processes matched the criteria" 1>&2
else
    echo "$STATUS No processes matched" 1>&2
fi
